### ISSUE TITLE
Lucia deprecated

### ISSUE THREAD

**Issue by ringge** [noxify/t3-turbo-lucia#11]
Hello, thanks for a great template. Yesterday Lucia announced its deprecation, any chance this template can be updated accordingly?
Many thanks

**Comment by noxify** [comment]
hi @ringge - have seen the announcement.

I'm currently working on updating the template to the latest version - but I'm currently busy at work and with my docs template.

Have to block some time to finish this.

To lucia: I would keep it, but will use their provided code snippets to implement it by my own ( need it at work, too ).

Have also seen "better auth", but haven't checked it in detail. ( but it seems to be more an alternative to authjs than lucia )

**Comment by ringge** [comment]
hey @noxify 
great to hear you have plan to update it, I also feel the way to go is use lucia's code snippets. Also looked at better-auth, but who knows whether better-auth later on may follow lucia's path :)

**Comment by dBianchii** [comment]
I just updated my repo to rolling my own auth based on lucia-auth's resources on https://lucia-auth.com/sessions/migrate-lucia-v3

At first I was sad that lucia was being deprecated, but now it just makes so much sense for me. I love that now I have complete independence from auth libraries and my code is much more understandable.

@noxify if this repo get's moved to the strategy on their docs, will you keep the name as 't3-turbo-lucia' still?

**Comment by noxify** [comment]
I would keep the repo name.

Have seen that there is a new package: https://github.com/gnk-softworks/narvik

Maybe switching to this could make sense, but copy&paste the code from the Lucia docs to create our "own" solution would work, too.

Using the new Lucia approach (by providing just the code to create your own) would reduce the risk to have an unmaintained package as dependency- but you - as developer - are responsible to ensure that everything works as expected and is secure. 

For me, it's okay - at the end, it's the same as for the shadcn components 🤷‍♂️

Unfortunately, I'm currently a bit busy with our internal projects.

What do you think?
